add_subdirectory("${CMAKE_SOURCE_DIR}/../CstDemo/Cst/System" ${CMAKE_BINARY_DIR}/CstDemo/Cst/System)
add_subdirectory(Framework)
add_subdirectory(FrameworkTest)
add_subdirectory(CstCore)
add_subdirectory(CstCli)
add_subdirectory(CstCoreTest)
if(USE_MONO)
  add_subdirectory(CstMono)
endif()
add_subdirectory(Mini)
