#define  FR_KEY_UNKNOWN        GLFW_KEY_UNKNOWN
#define  FR_KEY_SPACE          GLFW_KEY_SPACE
#define  FR_KEY_APOSTROPHE     GLFW_KEY_APOSTROPHE
#define  FR_KEY_COMMA          GLFW_KEY_COMMA
#define  FR_KEY_MINUS          GLFW_KEY_MINUS
#define  FR_KEY_PERIOD         GLFW_KEY_PERIOD
#define  FR_KEY_SLASH          GLFW_KEY_SLASH
#define  FR_KEY_0              GLFW_KEY_0
#define  FR_KEY_1              GLFW_KEY_1
#define  FR_KEY_2              GLFW_KEY_2
#define  FR_KEY_3              GLFW_KEY_3
#define  FR_KEY_4              GLFW_KEY_4
#define  FR_KEY_5              GLFW_KEY_5
#define  FR_KEY_6              GLFW_KEY_6
#define  FR_KEY_7              GLFW_KEY_7
#define  FR_KEY_8              GLFW_KEY_8
#define  FR_KEY_9              GLFW_KEY_9
#define  FR_KEY_SEMICOLON      GLFW_KEY_SEMICOLON
#define  FR_KEY_EQUAL          GLFW_KEY_EQUAL
#define  FR_KEY_A              GLFW_KEY_A
#define  FR_KEY_B              GLFW_KEY_B
#define  FR_KEY_C              GLFW_KEY_C
#define  FR_KEY_D              GLFW_KEY_D
#define  FR_KEY_E              GLFW_KEY_E
#define  FR_KEY_F              GLFW_KEY_F
#define  FR_KEY_G              GLFW_KEY_G
#define  FR_KEY_H              GLFW_KEY_H
#define  FR_KEY_I              GLFW_KEY_I
#define  FR_KEY_J              GLFW_KEY_J
#define  FR_KEY_K              GLFW_KEY_K
#define  FR_KEY_L              GLFW_KEY_L
#define  FR_KEY_M              GLFW_KEY_M
#define  FR_KEY_N              GLFW_KEY_N
#define  FR_KEY_O              GLFW_KEY_O
#define  FR_KEY_P              GLFW_KEY_P
#define  FR_KEY_Q              GLFW_KEY_Q
#define  FR_KEY_R              GLFW_KEY_R
#define  FR_KEY_S              GLFW_KEY_S
#define  FR_KEY_T              GLFW_KEY_T
#define  FR_KEY_U              GLFW_KEY_U
#define  FR_KEY_V              GLFW_KEY_V
#define  FR_KEY_W              GLFW_KEY_W
#define  FR_KEY_X              GLFW_KEY_X
#define  FR_KEY_Y              GLFW_KEY_Y
#define  FR_KEY_Z              GLFW_KEY_Z
#define  FR_KEY_LEFT_BRACKET   GLFW_KEY_LEFT_BRACKET
#define  FR_KEY_BACKSLASH      GLFW_KEY_BACKSLASH
#define  FR_KEY_RIGHT_BRACKET  GLFW_KEY_RIGHT_BRACKET
#define  FR_KEY_GRAVE_ACCENT   GLFW_KEY_GRAVE_ACCENT
#define  FR_KEY_WORLD_1        GLFW_KEY_WORLD_1
#define  FR_KEY_WORLD_2        GLFW_KEY_WORLD_2
#define  FR_KEY_ESCAPE         GLFW_KEY_ESCAPE
#define  FR_KEY_ENTER          GLFW_KEY_ENTER
#define  FR_KEY_TAB            GLFW_KEY_TAB
#define  FR_KEY_BACKSPACE      GLFW_KEY_BACKSPACE
#define  FR_KEY_INSERT         GLFW_KEY_INSERT
#define  FR_KEY_DELETE         GLFW_KEY_DELETE
#define  FR_KEY_RIGHT          GLFW_KEY_RIGHT
#define  FR_KEY_LEFT           GLFW_KEY_LEFT
#define  FR_KEY_DOWN           GLFW_KEY_DOWN
#define  FR_KEY_UP             GLFW_KEY_UP
#define  FR_KEY_PAGE_UP        GLFW_KEY_PAGE_UP
#define  FR_KEY_PAGE_DOWN      GLFW_KEY_PAGE_DOWN
#define  FR_KEY_HOME           GLFW_KEY_HOME
#define  FR_KEY_END            GLFW_KEY_END
#define  FR_KEY_CAPS_LOCK      GLFW_KEY_CAPS_LOCK
#define  FR_KEY_SCROLL_LOCK    GLFW_KEY_SCROLL_LOCK
#define  FR_KEY_NUM_LOCK       GLFW_KEY_NUM_LOCK
#define  FR_KEY_PRINT_SCREEN   GLFW_KEY_PRINT_SCREEN
#define  FR_KEY_PAUSE          GLFW_KEY_PAUSE
#define  FR_KEY_F1             GLFW_KEY_F1
#define  FR_KEY_F2             GLFW_KEY_F2
#define  FR_KEY_F3             GLFW_KEY_F3
#define  FR_KEY_F4             GLFW_KEY_F4
#define  FR_KEY_F5             GLFW_KEY_F5
#define  FR_KEY_F6             GLFW_KEY_F6
#define  FR_KEY_F7             GLFW_KEY_F7
#define  FR_KEY_F8             GLFW_KEY_F8
#define  FR_KEY_F9             GLFW_KEY_F9
#define  FR_KEY_F10            GLFW_KEY_F10
#define  FR_KEY_F11            GLFW_KEY_F11
#define  FR_KEY_F12            GLFW_KEY_F12
#define  FR_KEY_F13            GLFW_KEY_F13
#define  FR_KEY_F14            GLFW_KEY_F14
#define  FR_KEY_F15            GLFW_KEY_F15
#define  FR_KEY_F16            GLFW_KEY_F16
#define  FR_KEY_F17            GLFW_KEY_F17
#define  FR_KEY_F18            GLFW_KEY_F18
#define  FR_KEY_F19            GLFW_KEY_F19
#define  FR_KEY_F20            GLFW_KEY_F20
#define  FR_KEY_F21            GLFW_KEY_F21
#define  FR_KEY_F22            GLFW_KEY_F22
#define  FR_KEY_F23            GLFW_KEY_F23
#define  FR_KEY_F24            GLFW_KEY_F24
#define  FR_KEY_F25            GLFW_KEY_F25
#define  FR_KEY_KP_0           GLFW_KEY_KP_0
#define  FR_KEY_KP_1           GLFW_KEY_KP_1
#define  FR_KEY_KP_2           GLFW_KEY_KP_2
#define  FR_KEY_KP_3           GLFW_KEY_KP_3
#define  FR_KEY_KP_4           GLFW_KEY_KP_4
#define  FR_KEY_KP_5           GLFW_KEY_KP_5
#define  FR_KEY_KP_6           GLFW_KEY_KP_6
#define  FR_KEY_KP_7           GLFW_KEY_KP_7
#define  FR_KEY_KP_8           GLFW_KEY_KP_8
#define  FR_KEY_KP_9           GLFW_KEY_KP_9
#define  FR_KEY_KP_DECIMAL     GLFW_KEY_KP_DECIMAL
#define  FR_KEY_KP_DIVIDE      GLFW_KEY_KP_DIVIDE
#define  FR_KEY_KP_MULTIPLY    GLFW_KEY_KP_MULTIPLY
#define  FR_KEY_KP_SUBTRACT    GLFW_KEY_KP_SUBTRACT
#define  FR_KEY_KP_ADD         GLFW_KEY_KP_ADD
#define  FR_KEY_KP_ENTER       GLFW_KEY_KP_ENTER
#define  FR_KEY_KP_EQUAL       GLFW_KEY_KP_EQUAL
#define  FR_KEY_LEFT_SHIFT     GLFW_KEY_LEFT_SHIFT
#define  FR_KEY_LEFT_CONTROL   GLFW_KEY_LEFT_CONTROL
#define  FR_KEY_LEFT_ALT       GLFW_KEY_LEFT_ALT
#define  FR_KEY_LEFT_SUPER     GLFW_KEY_LEFT_SUPER
#define  FR_KEY_RIGHT_SHIFT    GLFW_KEY_RIGHT_SHIFT
#define  FR_KEY_RIGHT_CONTROL  GLFW_KEY_RIGHT_CONTROL
#define  FR_KEY_RIGHT_ALT      GLFW_KEY_RIGHT_ALT
#define  FR_KEY_RIGHT_SUPER    GLFW_KEY_RIGHT_SUPER
#define  FR_KEY_MENU           GLFW_KEY_MENU
#define  FR_KEY_LAST           GLFW_KEY_LAST

#define  FR_KEY_RELEASE  GLFW_RELEASE
#define  FR_KEY_PRESS    GLFW_PRESS
#define  FR_KEY_REPEAT   GLFW_REPEAT
