set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
)

FIND_PATH(SDL2_INCLUDE_DIR
  NAMES SDL2/SDL.h
  HINTS ${search_dirs}
  PATH_SUFFIXES sdl2/include
)

FIND_LIBRARY(SDL2_LIBRARY
  NAMES sdl2
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2 DEFAULT_MSG
  SDL2_LIBRARY SDL2_INCLUDE_DIR)

IF(SDL2_FOUND)
  SET(SDL2_LIBRARIES ${SDL2_LIBRARY})
  SET(SDL2_INCLUDE_DIRS ${SDL2_INCLUDE_DIR})
ENDIF(SDL2_FOUND)

MARK_AS_ADVANCED(
  SDL2_INCLUDE_DIR
  SDL2_LIBRARY
)
